### ISSUE TITLE
Launch the site

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1]
- [x] replace "gratipay" with "liberapay" in the code
- [x] clean up the DB schema (id as primary key everywhere, etc)
- [x] implement mandatory email+password auth
- [x] rework the UI including its theme (let's use Bootstrap)
- [x] modify the code to use MangoPay instead of Balanced (and € instead of $)
- [x] implement identity info collection (https://docs.mangopay.com/api-references/kyc-rules/)
- [x] reimplement teams
- [x] design a logo
- [x] widgets
- [x] protect ourselves from chargebacks (#2)
- [x] read https://www.mangopay.com/wp-content/uploads/2015/09/MANGOPAY_Contract-02_JAN_2015.pdf
- [x] write terms of service (https://github.com/liberapay/liberapay.org/issues/4)
- [x] register for a MangoPay account (https://github.com/liberapay/liberapay.org/issues/5)
- [x] complete the /about pages
- [x] figure out i18n infrastructure *(done: https://hosted.weblate.org/projects/liberapay/)*
- [x] i18n of the account closing page
- [x] get a certificate for TLS
- [x] figure out infrastructure for hosting & error logging & metrics ~~& email~~ *(we'll use Mandrill for now)*
- [x] 100% french translation

**Comment by MartinDelille** [comment]
I will ask a friend if he can propose a logo.

**Comment by Changaco** [comment]
Password auth done in #5, now working on the UI.

**Comment by whit537** [comment]
Best of luck, @Changaco, et al. :-)

I have started recommending Liberapay to people that aren't a good fit for Gratipay.

**Comment by Changaco** [comment]
Took longer than I'd hoped, but it's done: Liberapay has its own UI. \o/

![liberapay-v1](https://cloud.githubusercontent.com/assets/1581590/8159037/42b52fb2-1363-11e5-9b63-068244d53251.png)

**Comment by Changaco** [comment]
https://hosted.weblate.org/projects/liberapay/ is now synced, the new UI is less than 50% translated.

**Comment by Changaco** [comment]
After a rather lengthy pause (a month), I'm working on this again.

**Comment by Changaco** [comment]
Wooohooooo :tada: :cocktail: :cake:

There's still work to do, but that last PR brought us a lot closer to launch readiness.

**Comment by Changaco** [comment]
Also, the tests are finally passing on master and the fixtures are a lot smaller! \o/

**Comment by Changaco** [comment]
Now that the giant pull requests are done I'm dumping my local todo list into github issues so that other people (i.e. you) can see what still needs to be done and start contributing.

**Comment by Changaco** [comment]
The list of things missing before the site can be launched is getting short. :-)

**Comment by Changaco** [comment]
Relevant news: [Let's Encrypt is Entering Public Beta](https://letsencrypt.org//2015/12/03/entering-public-beta.html).

**Comment by Changaco** [comment]
By the way, I'm currently hoping and aiming to launch early next year (i.e. in less than 3 months).

**Comment by Changaco** [comment]
I've created separate issues in the org repo for the legal tasks: https://github.com/liberapay/liberapay.org/issues/4 and https://github.com/liberapay/liberapay.org/issues/5.

**Comment by Changaco** [comment]
I've also improved the temporary homepage of Liberapay at https://liberapay.com/ so people who land there can better understand what the project is.

**Comment by Changaco** [comment]
I've been looking deeper into hosting since we're on schedule for launch so far. My original thought was [Clever Cloud](https://www.clever-cloud.com/), however after looking into other Heroku alternatives I've found [OpenShift](https://www.openshift.com/) (Red Hat).

Advantages over Clever Cloud:

- They have a free plan, with pay-per-use for extra resources.
- They have [grants](https://www.openshift.com/grants/) for non-profits and open source projects.
- They're more open source and have better documentation and more add-ons.

Drawbacks I've found so far:

- They don't provide stable IP addresses to point to, so we have to either:
  - use a `CNAME`, which means using `www.liberapay.com` as the canonical name instead of the shorter `liberapay.com`
  - switch to a costlier registrar that implements a non-standard record (`ALIAS`/`ANAME`)
  - use [CloudFlare's DNS](https://www.cloudflare.com/dns/), apparently it's free and it would bypass the issue entirely, that seems like an acceptable solution
- Their free plan doesn't allow us to host in Europe.

**Comment by whit537** [comment]
@Changaco You gonna launch at [OuiShare Fest](http://2016.ouisharefest.com/)? :)

**Comment by Changaco** [comment]
@whit537 I'm not currently planning to attend OuiShare Fest, but I did notice that you're going this year, so maybe we can finally meet. I watched your [call with OuiShare](https://www.youtube.com/watch?v=dcaMkwFhyV0) last night, it was pretty good. :-)

**Comment by whit537** [comment]
Thanks! You got a mention, if I remember right ... [here it is](https://www.youtube.com/watch?v=dcaMkwFhyV0#t=38m49s). :-)

And I'd love to finally meet in person. :-) Reticketed as https://github.com/gratipay/inside.gratipay.com/issues/464.

**Comment by Changaco** [comment]
I've created [a salon](https://github.com/liberapay/salon) for the discussions that don't belong elsewhere, and kicked it off with a monthly "what's up?" thread: https://github.com/liberapay/salon/issues/1. I've posted a report on the status of the project in there.

**Comment by Changaco** [comment]
https://github.com/liberapay/liberapay.org/issues/5 is done, if the app was ready we could start processing payments right now! \o/ \o/ \o/ :tada: :birthday:

**Comment by whit537** [comment]
!m @Changaco

**Comment by Changaco** [comment]
We've started using [Git LFS](https://git-lfs.github.com/) in #69, but OpenShift doesn't have builtin support for that, and [I couldn't find a script to download the files](https://stackoverflow.com/questions/34027762/fetch-a-single-lfs-file-from-protected-github-repo/), so [I made one](https://github.com/liberapay/git-lfs-fetch.py).

**Comment by Changaco** [comment]
There's one more thing I want to get done before launching:

- [ ] 100% french translation

I'd also like to close as many [high priority issues](https://github.com/liberapay/liberapay.com/labels/High%20Priority) as possible.

If there's anyone lurking around here who was waiting to see if the site would really launch before contributing: well we are definitely launching, so you can start now.

**Comment by finkiki** [comment]
I start translating some strings. Tell me if I make that well.

**Comment by Changaco** [comment]
@finkiki You're doing it fine. I've corrected/improved a few of your translations (see [recent changes](https://hosted.weblate.org/changes/?lang=fr&project=liberapay&subproject=core)).

**Comment by finkiki** [comment]
How do you want to translate "team" ? "Équipe" is maybe not the good word.

**Comment by Changaco** [comment]
@finkiki "Équipe" is fine, I haven't found a better translation.

**Comment by finkiki** [comment]
And for "wallet" ?

**Comment by Changaco** [comment]
"porte-monnaie" or "portefeuille", whichever you prefer. Can also be "compte" depending on the context.

**Comment by Changaco** [comment]
We should talk about this somewhere else, let's go in the salon: https://github.com/liberapay/salon/issues/2.

**Comment by Changaco** [comment]
[Sentry's hosting pricing](https://getsentry.com/pricing/) seems a bit high to me, so I've set up [an instance on my personal server](https://sentry.changaco.oy.lc/) (as often, ArchLinux has [a package](https://aur.archlinux.org/packages/sentry/) for it that came in handy).

**Comment by Changaco** [comment]
The About pages are done, and @finkiki is working on the french translation, so I'm going to focus on getting Liberapay running on OpenShift.

**Comment by Changaco** [comment]
We're almost done with the French translation, mostly thanks to @finkiki, and I've acquired an understanding of the OpenShift platform.

The plan is: this week we finish the fr translation and the adaptation to OpenShift, we also get rid of a few high priority issues, and next week we launch!

**Comment by Changaco** [comment]
Done! \o/ [liberapay.com](https://liberapay.com/) is up and running! The thread to coordinate spreading the word is https://github.com/liberapay/salon/issues/3. :-)

**Comment by Changaco** [comment]
@finkiki Tell me when you've created your account so I can add you to the Liberapay team.

**Comment by whit537** [comment]
!m @Changaco :-)

**Comment by MartinDelille** [comment]
Well done @Changaco ! I follow the project from the beginning and regret not having contribute to it... At least I'm now the [main founder for liberapay](https://liberapay.com/martindelille/giving/) now! :-) (but it won't last for long I'm sure)

**Comment by Changaco** [comment]
Thanks @MartinDelille :-) It's never too late to start contributing, there's still plenty to do. Note: the `/giving/` page is private, only you (and me, as an admin) can see it.

**Comment by finkiki** [comment]
Well done ! But I do very little for the launch.

**Comment by Changaco** [comment]
@finkiki I've sent you an invite, you did a big chunk of the French translation, it must have taken you hours, and we want and need our translators to share in the income of the team.

**Comment by finkiki** [comment]
Thanks!
